### ISSUE TITLE
ProgressBar looking different on API 23 and API 30

### ISSUE THREAD

**Issue by leinardi** [muramrr/ProgressButton_MotionLayout#1]
First of all thank you for this project. I just want to report a UI bug (and its fix) that I'm experiencing on API 23:

![image](https://user-images.githubusercontent.com/273338/109018757-accb5980-76b8-11eb-8088-eb178ffb116f.png)

On API 23 the card is adding some kind of internal padding that is messing with the progress.

This is how the same code looks on API 30:
![image](https://user-images.githubusercontent.com/273338/109018921-d08e9f80-76b8-11eb-83bc-7d4409f5fa73.png)

To fix this you just have to add the following attribute to the card view:
```xml
app:cardPreventCornerOverlap="false"
```

And then it will look way better also on API 23:
![image](https://user-images.githubusercontent.com/273338/109019211-13507780-76b9-11eb-8352-0650b669c78b.png)

I would suggest to update also the dependencies to use the latest stable versions:
```Groovy
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'com.google.android.material:material:1.3.0'
```

**Comment by muramrr** [comment]
Hi! Thank you for the issue. 
I'll update all of this stuff as soon as possible!
